[tool.black]
line-length = 130
target-version = ['py37']
include = '\.pyi?$'

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "no-member",
  "import-error",
  "no-name-in-module",
  "useless-super-delegation",
  "too-few-public-methods",
  "redefined-builtin",
]

[tool.pyright]
pythonVersion = '3.7'
venvPath = '.'
venv = '.venv'


